### ISSUE TITLE
Request: Update the Components and supplies

### ISSUE THREAD

**Issue by santaimpersonator** [dbduino-prjs/spkfn-weather-station-arduino-cloud#7]
Could you update the products listed in the **Components and supplies** section?

![image](https://github.com/dbduino-prjs/spkfn-weather-station-arduino-cloud/assets/36016723/d830e9f8-1368-46c0-8783-38182432eada)

We would like to replace the individually listed components with the new [SparkFun Arduino IoT Weather Station](https://www.sparkfun.com/products/22636) kit.

**Comment by d-beamon** [comment]
Fixed here https://projecthub.arduino.cc/dbeamonte_arduino/weather-station-with-arduino-cloud-20ce95
